--- #YAML:1.0
name:               Git-Export
version:            0.04
abstract:           git equivalent to 'svn export'
author:
    - Casiano Rodriguez-Leon <casiano@ull.es>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Copy::Recursive:  0
    File::Path:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
